title: Maximiliano Aguirre's blog

author:
  name: Maximiliano Aguirre
  email: maximiliano.aguirre@outlook.es

remote_theme: jekyll/minima

minima:
  skin: dark

  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/maximilianoaguirre/" }
    - { platform: github,         user_url: "https://github.com/MaximilianoAguirre" }
