title: Tech blog
subtitle: by Maxi
name: &name Maximiliano Aguirre

remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: dark

baseurl: /blog
enable_copy_code_button: true

footer:
  links:
    - label: Linkedin
      url: https://www.linkedin.com/in/maximilianoaguirre
      icon: fa-brands fa-linkedin
    - label: Github
      url: https://github.com/MaximilianoAguirre
      icon: fa-brands fa-github
    - label: "Web"
      icon: "fas fa-fw fa-link"
      url: "https://maximilianoaguirre.com"
    - label: Instagram
      url: https://www.instagram.com/maxii3548/
      icon: fa-brands fa-instagram
    - label: Mail
      url: mailto:maximiliano.aguirre@outlook.es
      icon: fa-solid fa-envelope

author:
  name: *name
  avatar: /assets/profile.jpg
  bio: Tech guy that loves extreme sports

  links:
    - label: Linkedin
      url: https://www.linkedin.com/in/maximilianoaguirre
      icon: fa-brands fa-linkedin
    - label: Github
      url: https://github.com/MaximilianoAguirre
      icon: fa-brands fa-github
    - label: Website
      icon: fas fa-fw fa-link
      url: "https://maximilianoaguirre.com"
    - label: Instagram
      url: https://www.instagram.com/maxii3548/
      icon: fa-brands fa-instagram
    - label: Email
      url: mailto:maximiliano.aguirre@outlook.es
      icon: fa-solid fa-envelope

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
