title: Maximiliano Aguirre's blog

remote_theme: jekyll/minima

minima:
  skin: dark

  social_links:
    - platform: linkedin
      user_url: https://www.linkedin.com/in/maximilianoaguirre/
      title: Linkedin
    - platform: github
      user_url: https://github.com/MaximilianoAguirre
      title: Github
    - platform: mail
      user_url: mailto:maximilianoaguirre@outlook.es
      title: Mail
