title: Maximiliano Aguirre's blog

author:
  name: Maximiliano Aguirre
  email: maximiliano.aguirre@outlook.es

description: Blog dedicated to technical topics


remote_theme: jekyll/minima

minima:
  skin: dark

  social_links:
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/maximilianoaguirre/",
      }
    - { platform: github, user_url: "https://github.com/MaximilianoAguirre" }
    - { platform: mail, user_url: "mailto:maximilianoaguirre@outlook.es" }
